// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackApi.Models;

public partial class Pelicula
{
    public int id { get; set; }

    public string titulo { get; set; }

    public string director { get; set; }

    public int anio { get; set; }

    public bool estreno { get; set; }

    public int id_genero { get; set; }

    public virtual Genero id_generoNavigation { get; set; }
}